name: "PowerShell Dependencies"
description: "Generates Markdown documentation based on comments in your PS-module"

runs:
  using: "composite"
  steps:
    - run: echo Installing dependencies
      shell: bash
    - id: install-dependencies
      run: . ./install-dependencies.ps1
      shell: pwsh
    - run: Install-Dependencies -path "${{ github.action_path }}"
      shell: pwsh
