# This workflow will run PowerShell tests on Windows, Linux and macOS
name: PowerShell

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        shell: pwsh
        run: |
          if (Test-Path 'requirements.txt') {
            Get-Content 'requirements.txt' | ForEach-Object {
              $module = $_ -split "="
              if ($module.count -gt 1) {
                Install-Module -Name $module[0] -MinimumVersion $module[1] -Force -SkipPublisherCheck
              }
              else {
                Install-Module -Name $module[0] -Force -SkipPublisherCheck
              }
            }
          }

      - name: Install Pester
        shell: pwsh
        run: Instll-Module -Name Pester -Force -SkipPublisherCheck -MinimumVersion '5.0'

      - name: Test Modules in src
        shell: pwsh
        run: |
          Invoke-Perster -Path ./src/* -CI
