on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v1
      - id: foo
        uses: actions/powershell-actions@v1
        with:
          who-to-greet: "raiden-e"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
